### ISSUE TITLE
Where to put the maps on Oculus Quest?

### ISSUE THREAD

**Issue by shaack** [OddersLab/OhShapeEditor#2]
I use "Android file Transfer" to transfer files from my MacBook to my Quest. But there ist no "/My Documents/OhShape/Songs" folder. Do I have to create this folder?

**Comment by OddersLab** [comment]
Hello Stefan,

You have to put the custom maps here: (root)/OhShape/Songs -> this Folder
is automatically generated by the game.

Best,
Daniel
